function extractCity(text: string): string | null {
  const cities = [
    'Airdrie',
    'Athabasca',
    'Banff',
    'Beaumont',
    'Black Diamond',
    'Blackfalds',
    'Bon Accord',
    'Bow Island',
    'Brooks',
    'Calgary',
    'Camrose',
    'Canmore',
    'Cardston',
    'Carstairs',
    'Chestermere',
    'Claresholm',
    'Coaldale',
    'Cochrane',
    'Cold Lake',
    'Coronation',
    'Crossfield',
    'Drumheller',
    'Didsbury',
    'Devon',
    'Edmonton',
    'Edson',
    'Eckville',
    'Fairview',
    'Fort McMurray',
    'Fort Saskatchewan',
    'Grande Prairie',
    'High Level',
    'High River',
    'Hinton',
    'Innisfail',
    'Lacombe',
    'Leduc',
    'Lethbridge',
    'Lloydminster',
    'Medicine Hat',
    'Olds',
    'Okotoks',
    'Peace River',
    'Penhold',
    'Ponoka',
    'Raymond',
    'Red Deer',
    'Rocky Mountain House',
    'Saint Albert',
    'Sherwood Park',
    'Spruce Grove',
    'St. Paul',
    'Stettler',
    'Stony Plain',
    'Strathmore',
    'Sylvan Lake',
    'Taber',
    'Trochu',
    'Valleyview',
    'Vegreville',
    'Vermilion',
    'Wetaskiwin',
    'Whitecourt',
  ];

  const lower = text.toLowerCase();
  return cities.find((c) => lower.includes(c)) ?? null;
}
export { extractCity };
